
hook.Add("PopulateToolMenu","EZ_MENU",function()
spawnmenu.AddToolMenuOption("Options","EZ SWEP Settings","EZ_Settings","Settings","","",function(pnl)
pnl:ClearControls()
pnl:AddControl( "CheckBox", { Label = "No Recoil", Command = "sk_ez_no_recoil" } )
pnl:AddControl( "CheckBox", { Label = "No Bullet Spread", Command = "sk_ez_no_bullet_spread" } )
pnl:AddControl( "CheckBox", { Label = "Infinite ammo", Command = "sk_ez_infinite_ammo" } )
pnl:AddControl( "Slider", { Label = "AR2 Damage", Type = "Integer", Command = "sk_ez_proto_ar2_dmg", Min = "0", Max = "100" } )
pnl:AddControl( "Slider", { Label = "AR2 Bullet Num", Type = "Integer", Command = "sk_ez_proto_ar2_num", Min = "0", Max = "10" } )
pnl:AddControl( "Slider", { Label = "AR2 Ball Explode Time", Type = "Integer", Command = "sk_ez_proto_ar2_ball_explode_time", Min = "0", Max = "100" } )
pnl:AddControl( "Slider", { Label = "MP5K Damage", Type = "Integer", Command = "sk_ez2_mp5k_dmg", Min = "0", Max = "100" } )
pnl:AddControl( "Slider", { Label = "Pulse Pistol Damage", Type = "Integer", Command = "sk_ez2_pulse_pistol_dmg", Min = "0", Max = "100" } )
pnl:AddControl( "Button", { Label = "Reset Commands", Command = "sk_ez_no_recoil 0 \n sk_ez_no_bullet_spread 0 \n sk_ez_infinite_ammo 0 \n sk_ez_proto_ar2_dmg 16 \n sk_ez_proto_ar2_num 2 \n sk_ez2_mp5k_dmg 8 \n sk_ez2_pulse_pistol_dmg 15 \n sk_ez_proto_ar2_ball_explode_time" } )
end)
end)