
hook.Add("AddToolMenuTabs", "EZ_ADDMENU", function()
	spawnmenu.AddToolCategory("Options", "EZ Settings", "#ez_swep.swep.settings")
end)

hook.Add("PopulateToolMenu","EZ_MENU",function()
	spawnmenu.AddToolMenuOption("Options","EZ Settings","EZ_Settings","#ez_swep.settings","","",function(pnl)
	pnl:ClearControls()
	pnl:AddControl( "CheckBox", { Label = "#ez_swep.no.recoil", Command = "ez_swep_no_recoil" } )
	pnl:AddControl( "CheckBox", { Label = "#ez_swep.no.bullet.spread", Command = "ez_swep_no_bullet_spread" } )
	pnl:AddControl( "CheckBox", { Label = "#ez_swep.infinite.ammo", Command = "ez_swep_infinite_ammo" } )
	pnl:AddControl( "CheckBox", { Label = "#ez_swep.firstdraw.animation", Command = "ez_swep_firstdraw_animation" } )
	pnl:ControlHelp( "#ez_swep.firstdraw.animation.desc" )
	pnl:AddControl( "CheckBox", { Label = "#ez_swep.firstdraw.by_reload", Command = "ez_swep_firstdraw_by_reload" } )
	pnl:ControlHelp( "#ez_swep.firstdraw.by_reload.desc" )
	pnl:AddControl( "CheckBox", { Label = "#ez_swep.lower_on_ally", Command = "ez_swep_lower_on_ally" } )
	pnl:ControlHelp( "#ez_swep.lower_on_ally.desc" )
	pnl:AddControl( "Slider", { Label = "#ez_swep.fov", Type = "Integer", Command = "ez_swep_fov", Min = "0", Max = "180" } )
	pnl:AddControl( "Slider", { Label = "#ez_swep.ar2.dmg", Type = "Integer", Command = "sk_ez_proto_ar2_dmg", Min = "0", Max = "100" } )
	pnl:AddControl( "Slider", { Label = "#ez_swep.ar2.bullet.num", Type = "Integer", Command = "sk_ez_proto_ar2_num", Min = "0", Max = "10" } )
	pnl:AddControl( "Slider", { Label = "#ez_swep.ar2.ball.explode.time", Type = "Integer", Command = "sk_ez_proto_ar2_ball_explode_time", Min = "0", Max = "100" } )
	pnl:AddControl( "Slider", { Label = "#ez_swep.mp5k.dmg", Type = "Integer", Command = "sk_ez2_mp5k_dmg", Min = "0", Max = "100" } )
	pnl:AddControl( "Slider", { Label = "#ez_swep.pulse.pistol.dmg", Type = "Integer", Command = "sk_ez2_pulse_pistol_dmg", Min = "0", Max = "100" } )
	pnl:AddControl( "Button", { Label = "#ez_swep.reset.commands", Command = "ez_swep_no_recoil 0 \n ez_swep_no_bullet_spread 0 \n ez_swep_infinite_ammo 0 \n sk_ez_proto_ar2_dmg 16 \n sk_ez_proto_ar2_num 2 \n sk_ez2_mp5k_dmg 8 \n sk_ez2_pulse_pistol_dmg 15 \n sk_ez_proto_ar2_ball_explode_time 1" } )
	end)
end)